apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strategyforge
  namespace: strategyforge
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
spec:
  rules:
    - host: strategyforge.example
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: php-api
                port:
                  number: 80
          - path: /rag/
            pathType: Prefix
            backend:
              service:
                name: rag-service
                port:
                  number: 8001
          - path: /game_widget.html
            pathType: Prefix
            backend:
              service:
                name: php-api
                port:
                  number: 80
          - path: /godot/
            pathType: Prefix
            backend:
              service:
                name: php-api
                port:
                  number: 80
